import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Header } from "../components/Header.tsx";
import { Toaster } from "../components/ui/toaster.tsx";
import { UserProvider } from "../hooks/useUser.tsx";
import ReactQueryProvider from "../utils/providers/ReactQueryProvider.tsx";
import { ThemeProvider } from "../utils/providers/ThemeProvider.tsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"antialiased"}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <UserProvider>
              <Header />
              <main>
                {children}
              </main>
              <Toaster />
            </UserProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
