import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Toaster } from "../components/ui/toaster";
import { UserProvider } from "../hooks/useUser";
import ReactQueryProvider from "../utils/providers/ReactQueryProvider";
import { ThemeProvider } from "../utils/providers/ThemeProvider";
import { SidebarInset, SidebarProvider } from "../components/ui/sidebar";
import { AppSidebar } from "../components/Sidebar";
import { AppHeader } from "../components/Headers/AppHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <UserProvider>
              <SidebarProvider defaultOpen={false} className={"bg-sidebar"}>
                <AppSidebar />
                <SidebarInset className="rounded-md">
                  <AppHeader />
                  <main>{children}</main>
                </SidebarInset>
              </SidebarProvider>
              <Toaster />
            </UserProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
